### ISSUE TITLE
Pagination showing vertically instead of horizontally

### ISSUE THREAD

**Issue by Olamyy** [jmcclell/django-bootstrap-pagination#65]
Hi,
I'm attempting to use this package but for some reason, I seem to be getting the pagination list horizontally instead of vertically.
Is there something I'm missing or should check out to fix this?

Thanks.

**Comment by vnlinh112** [comment]
You can write your own css:
```css
ul.pagination li {
    display: inline;
}

ul.pagination li a {
    position: relative;
    float: left;
    padding: 0.5rem 0.75rem;
    margin-left: -1px;
    color: #5cb85c;
    text-decoration: none;
    background-color: #fff;
    border: 1px solid #ddd;
}

ul.pagination li span, ul.pagination li a:hover {
    position: relative;
    float: left;
    padding: 0.5rem 0.75rem;
    margin-left: -1px;
    text-decoration: none;
    border: 1px solid #ddd;
    color: #fff;
    border-color: #5cb85c;
    background-color: #5cb85c;
}

ul.pagination li:first-child a, ul.pagination li:first-child span {
    margin-left: 0;
    border-bottom-left-radius: 0.25rem;
    border-top-left-radius: 0.25rem;
}

ul.pagination li:last-child a, ul.pagination li:last-child span {
    margin-right: 0;
    border-bottom-right-radius: 0.25rem;
    border-top-right-radius: 0.25rem;
}
```
